name: workflow-call

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch: 
    
jobs:

  job1:
    runs-on: ubuntu-latest    

    steps:
      - name: Set color
        id: set-color-var
        run: echo "vapps={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> "$GITHUB_OUTPUT"
    outputs:
      vapps: ${{ steps.set-color-var.outputs.vapps }}        
                
  get-color:
    runs-on: windows-latest
    needs: job1
    strategy:
     matrix:
        host: ${{ 1 }}
    steps:
      - name: power & sleep
        run: echo "power & sleep ${{ matrix.host }}"
      
      - name: .net install
        run: echo ".net install ${{ matrix.host }}"
