# D:\a\packer-vsphere\packer-vsphere
name: workflow-call

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:

env:
  buildPath: 'DemoPath1'
  
  
    
jobs:

  job1:
    runs-on: ubuntu-latest    
    outputs:
      vapps: ${{ steps.random-color-generator.outputs.vapps }}
    steps:
      - name: Set color
        id: random-color-generator
        run: echo "vapps=green" >> "$GITHUB_OUTPUT"
        
        
  job2:
    runs-on: windows-latest
    needs: job1
    steps:
      - name: Get color
        run: echo "The selected color is ${{ job1.outputs.vapps }}"

  
