name: workflow-call

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch: 
    
jobs:

  job1:
    runs-on: ubuntu-latest    

    steps:
      - name: Set color
        id: set-color-var
        run: echo "vapps=={'vapp_id':'operation-0', 'ip_address':'149.212.205.62'}" >> "$GITHUB_OUTPUT"
    outputs:
      vapps: ${{ steps.set-color-var.outputs.vapps }}        
                
  get-color:
    runs-on: windows-latest
    needs: job1
    strategy:
     matrix:
        host: [1,2]
    steps:
      - name: Get color
        run: echo "The selected color is ${{ matrix.host }}" 
