name: workflow-call

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch: 
    
jobs:

  set-color:
    runs-on: ubuntu-latest    
    outputs:
      vapps: ${{ steps.set-color-var.outputs.vapps }}
    steps:
      - name: Set color
        id: set-color-var
        run: echo "vapps=green" >> "$GITHUB_OUTPUT"           
  
  get-color:
    runs-on: windows-latest
    needs: set-color
    steps:
      - name: Get color
        run: echo $set-color.outputs.vapps
