# D:\a\packer-vsphere\packer-vsphere
name: workflow-call

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:

env:
  buildPath: 'DemoPath'
  
  
    
jobs:

  job1:
    runs-on: ubuntu-latest    
    outputs:
      vapps: ${{ steps.step1.outputs.var1 }}
    steps:
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

  
