name: Clone & Execute
on:
  workflow_call:
    inputs:
     prod:
      required: true
      type: string

jobs:
  install:
    runs-on: [windows-latest]
    steps:     
      - name: Installation         
        run: Write-Host "Installation for ${{ inputs.prod }}"

  test:
   needs: install
   uses: sagartrivedi11/packer-vsphere/.github/workflows/test-execute.yml@main
   with:
    prod: ${{inputs.prod}}
