name: Workflow
on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: [windows-latest]
    steps:     
      - name: Start Test         
        run: |
          Write-Host "Test"

  job-2:
    runs-on: [windows-latest]
    needs: [job-1]
    timeout-minutes: 1
    steps:
      - name: Print cloned VM information         
        run: |
          sleep 65

  retry-job-2:
    runs-on: [ubuntu-latest]
    needs: [job-2]
    if: ${{ failure() }}
    steps:
      - name: Trigger Retry for job-2
        uses: actions/checkout@v2
      - name: Retry job-2
        run: echo "Retrying job-2"

  job-3:
    runs-on: [windows-latest]
    needs: ${{ github.event_name == 'workflow_dispatch' && failure() && needs.retry-job-2 != null && needs.retry-job-2.result == 'failure' ? 'retry-job-2' : 'job-2' }}
    steps:     
      - name: Start Test         
        run: |
          Write-Host "Test"
