name: Auto Trigger
on:
  workflow_dispatch:
   inputs:
    runid:
      description: 'run id'
      required: false  

env:
 variable1: 'test'


jobs:
  create:
    runs-on: [windows-latest]      
    steps:  
      - name: Start trigger
        run: |
         sleep 20
