name: Part2
run-name: Part2 [${{ github.event.inputs.location }}]
on:
  workflow_call:
    inputs:
      location:
        description: 'location '
        default: ""
        required: true
        type: string      
  
  
jobs:
  job1:
    
    runs-on: [windows-latest]      
    steps:  
      - name: step1
        run: |
          echo "Hello"                         
  job2:
    needs: [job1]
    runs-on: [windows-latest]      
    steps:
      - name: step1
        run: |
          echo "World" 
