name: Workflow
on:
  workflow_run:
    workflows: ["Workflow"]
    types:
      - completed

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check if previous run failed
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const previousRunStatus = await github.actions.getWorkflowRun({ owner: context.repo.owner, repo: context.repo.repo, run_id: context.payload.workflow_run.id });
            if (previousRunStatus.data.conclusion !== 'success') {
              console.log('Previous run failed. Restarting the workflow...');
              process.exit(1);
            }

  job-1:
    runs-on: windows-latest
    needs: check-status
    steps:     
      - name: Start Machine
        run: |
          Write-Host "Test"

  job-2:
    runs-on: windows-latest
    needs: [job-1]
    steps:     
      - name: Start Test         
        run: |
          Write-Host "Test"
