name: Part1
on:
  workflow_dispatch:
  workflow_call:    
  

env:
 variable1: 'test'


jobs:
  create:
    runs-on: [windows-latest]      
    steps:  
      - name: step1
        run: echo "First Job"    
  build:
      uses: sagartrivedi11/packer-vsphere/.github/workflows/part2.yml@main
      needs: create
