name: Part3
on:
  workflow_call:
  workflow_dispatch:

jobs:
  Part3-Job1:
    runs-on: [windows-latest]
    steps:     
      - name: Start Test         
        run: |
          Write-Host "Test"

  job-2:
    runs-on: [windows-latest]
    needs: [Part3-Job1]
    steps:
      - name: Step1   
        id: clone
        run: sleep 10
