name: Part2
inputs:
  location:
    description: 'location '
    default: ""
    required: true
    type: string      
  
runs:
 using: "composite"
 steps:  
    - name: step1
      run: echo "Hello"                           
          
        
