name: Part2
run-name: Part2 [${{ github.event.inputs.location }}]
on:
  workflow_dispatch:
    inputs:
      location:
        description: 'location '
        default: ""
        required: true
        type: string      
  
  
jobs:
  job1:
    
    runs-on: [windows-latest]  
    
    steps:
      - uses: actions/checkout@v3      

      - name: step1
        run: |
          echo "Hello"          
          
      - name: step2
        run: |
          echo "World"
        

        
  job2:
    needs: [job1]
    continue-on-error: true
    runs-on: [windows-latest]  
    
    steps:
      - uses: actions/checkout@v3      

      - name: step1
        run: |
          echo "Hello"          
          
      - name: step2
        run: |
          exit 2 

        
