name: Part2
on:
  workflow_call:
  workflow_dispatch:

jobs:
  Part2-Job1:
    runs-on: [windows-latest]
    steps:     
      - name: Start Test         
        run: |
          Write-Host "Test"

  Part2-Job12:
    runs-on: [windows-latest]
    needs: [Part2-Job1]
    steps:
      - name: Step1   
        id: clone
        timeout-minutes: 1
        run: sleep 65

  Part2-Job3:
    uses: sagartrivedi11/packer-vsphere/.github/workflows/part3.yml@main
