name: Part1
on:
  workflow_dispatch:
   inputs:
    location:
      description: 'Location'
      default: 'default_location'
      required: false
      type: string
  

env:
 variable1: 'test'


jobs:
  create:
    runs-on: [windows-latest]      
    steps:  
      - name: step1
        run: echo "First Job"    
  build:
    runs-on: windows-latest
    steps:
      - name: Reusable Workflow Call
        uses: sagartrivedi11/packer-vsphere/.github/workflows/part2.yml@main
        with:
          location: ${{ github.event.inputs.location }}
