name: Part2
run-name: Part2 
on:
  workflow_dispatch:

jobs:
  clone:
   runs-on: [windows-latest]
   timeout-minutes: 2
   steps:
        
     - name: Print cloned VM information         
       run: |
        sleep 3
     
  test:
   runs-on: [windows-latest]
   needs: [clone]
        
   steps:     
     - name: Start Test         
       run: |
         Write-Host "Test"
