name: Part1
on:
  workflow_dispatch:

env:
 variable1: 'test'


jobs:
  build:
    runs-on: windows-latest    
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Variable value is ${{ env.variable1 }}"
      - name: Run Part2 workflow
        uses: ./.github/workflows/part2.yml
        with:
          location: ${{ github.event.inputs.location }}
