name: Part1
on:
  workflow_dispatch:
   inputs:
    location:
      description: 'Location'
      default: 'default_location'
      required: false
      type: string
  

env:
 variable1: 'test'


jobs:
  build:
    runs-on: windows-latest    
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Variable value is ${{ env.variable1 }}"
      - name: Run Part2 workflow
        uses: sagartrivedi11/packer-vsphere/.github/workflows/part2.yml@main
        with:
          location: ${{ github.event.inputs.location }}
