name: Part2
run-name: Part2 [${{ inputs.location }}]
on:
  workflow_dispatch:
    inputs:
      location:
        description: 'location '
        default: ""
        required: true
        type: string      
  workflow_call:
    inputs:
      location:
        description: 'location '
        default: ""
        required: true
        type: string       
  
jobs:
  test-discover:
    
    runs-on: [windows-latest]      
    steps:  
      - name: step1
        run: echo "${{ inputs.location }}"      
        
  test-execution:
    needs: [test-discover]
    runs-on: [windows-latest]      
    steps:
      - name: step1
        run: echo "${{ inputs.location }}" 
