name: Auto Trigger
on:
  workflow_dispatch:
   inputs:
    runid:
      description: 'run id'
      required: false  

env:
 variable1: 'test'


jobs:
  create:
    runs-on: [windows-latest]      
    steps:  
      - name: Start trigger
        run: |
         $headers = @{
         "Authorization" = "token ${{ secrets.TOKEN }}"
         "Accept" = "application/vnd.github+json"
         }
         $body = @{
         "ref" = "main"
         }
         Invoke-RestMethod -Method Post -Headers $headers -Body ($body | ConvertTo-Json) -Uri "https://api.github.com/repos/sagartrivedi11/packer-vsphere/actions/runs/${{ github.event.inputs.run-id }}/rerun"
        
