# D:\a\packer-vsphere\packer-vsphere
name: workflow-call

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
  
  
    
jobs:

  job1:
    runs-on: windows-latest    
    outputs:
      vapps: ${{ steps.step1.outputs.var1 }}
    steps:
     - name: Output Run ID
       id: step1
       run: echo "var1=$hello" >> $GITHUB_OUTPUT
     - name: Output print
       run: echo "Output [${{ steps.step1.outputs.vapps }}]"
