name: workflow-call

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
    
jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: print array      
      run: echo 'Running'
