# D:\a\packer-vsphere\packer-vsphere
name: workflow-call

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
  
env:
 password: '{{ secrets.TEST_PASSWORD }}'
    
jobs:
  checkout:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: "actions/checkout@v3"
      - name: print pass      
        run: echo '{{env.password}}'
