# D:\a\packer-vsphere\packer-vsphere
name: workflow-call

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
  
  
    
jobs:
  job1:
    runs-on: windows-latest

    steps:
     - name: Output Run ID
       run: echo ${{ github.run_id }}
     - name: Output Run Number
       run: echo ${{ github.run_number }}
     - name: Output Run Attempt
       run: echo ${{ github.run_attempt }}
