name: workflow-call

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
    
jobs:
  checkout:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: "actions/checkout@v3"
        with:
          repository: sample/tools
          path: tools
      - name: print array      
        run: echo 'Running'
