name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: wait
        run: sleep 90
      - name: Run Step 1
        run: |
          # Perform Step 1 actions here
          echo "step1_completed=true" >> $GITHUB_ENV

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Step 1 Completion
        run: |
          while [[ "${{ env.step1_completed }}" != "true" ]]; do
            sleep 1
          done

      - name: Run Step 2
        run: |
          # Perform Step 2 actions here
