name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Perform your build/test steps here
     
      - name: wait
        run: sleep 60
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}/sample.exe

  download-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
   
      
      - name: Retrieve artifact information
        id: artifact-info
        run: |
          response=$(curl -sS -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                     "https://api.github.com/repos/${{ github.repository }}/actions/artifacts")
          download_url=$(echo "$response" | jq -r '.artifacts[] | select(.name == "my-artifact") | .archive_download_url')
          echo "::set-output name=download_url::$download_url"

      - name: Download artifact
        id: download
        run: |
          while true; do
            echo "Downloading artifact..."
            curl -LO "$(echo "${{ steps.artifact-info.outputs.download_url }}" | sed 's/\&/\\&/g')"
            if [[ -f "${{ github.workspace }}/sample.exe" ]]; then
              echo "Artifact downloaded successfully."
              break
            fi
            echo "Artifact download failed. Retrying in 5 seconds..."
            sleep 5
          done

      - name: Use downloaded artifact
        if: steps.download.conclusion == 'success'
        run: |
          # Use the downloaded artifact here
          echo "Artifact is ready to be used."
