name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
env:
  data: "[{'id': 't-0', 'ip_address': '1','template':'temp1','wait':30}, {'id': 't-1', 'ip': '11','template':'temp2','wait':600}]"

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Set Run ID as Artifact
        run: |
          echo "${{ github.run_id }}" > run_id.txt
          echo "::set-output name=artifact_path::run_id.txt"
      
    outputs:
          artifact_path: ${{ steps.set_run_id.outputs.artifact_path }}

  job2:
    runs-on: ubuntu-latest

    needs: job1

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: run-id-artifact
          path: artifacts

      - name: Read Run ID from Artifact
        run: |
          runId=$(cat artifacts/run_id.txt)
          echo "The run ID is: $runId"
