name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
env:
  data: "[{'id': 't-0', 'ip_address': '1','template':'temp1','wait':30}, {'id': 't-1', 'ip': '11','template':'temp2','wait':600}]"

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Set Run ID as Artifact
        run: echo "::set-output name=artifact_path::1"
      
    outputs:
          artifact_path: ${{ steps.set_run_id.outputs.artifact_path }}

  job2:
    runs-on: ubuntu-latest

    needs: job1

    steps:

      - name: Read Run ID from Artifact
        run: echo "The run  ${{needs.job1.outputs.artifact_path}}"
