name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Perform your build/test steps here
     
      - name: wait
        run: sleep 60
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}/sample.exe

  download-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for artifact
        id: wait
        run: |
          while true; do
            echo "Checking for artifact..."
            response=$(curl -sS -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                       "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts")
            download_url=$(echo "$response" | jq -r '.artifacts[] | select(.name == "my-artifact" and .state == "completed") | .archive_download_url')
            if [[ -n "$download_url" ]]; then
              echo "::set-output name=download_url::$download_url"
              break
            fi
            echo "Artifact not found or not completed. Retrying in 5 seconds..."
            sleep 5
          done

      - name: Download artifact
        id: download
        run: |
          curl -LO "$(echo "${{ steps.wait.outputs.download_url }}" | sed 's/\&/\\&/g')"
          echo "Artifact downloaded successfully."

      - name: Use downloaded artifact
        if: steps.download.conclusion == 'success'
        run: |
          # Use the downloaded artifact here
          echo "Artifact is ready to be used."
