name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
    
jobs:

  job1:
    runs-on: ubuntu-latest    

    steps:
      - name: Set color
        env:
         test: "[{'vapp_id': 'loadtest-0', 'ip_address': '149.212.205.9'}, {'vapp_id': 'loadtest-1', 'ip_address': '149.212.205.11'}]"
        id: set-color-var
        run: echo "vapps=${{ env.test }}" >> "$GITHUB_OUTPUT"
    
      - name: set product
        env:
         setup: "[product1,product2]"
        id: set-product
        run: echo "product=${{ env.setup }}" >> "$GITHUB_OUTPUT"
       
         
         
    outputs:
      vapps: ${{steps.set-color-var.outputs.vapps}} 
      product: ${{ steps.set-product.outputs.product }}
                
  get-color:
    runs-on: windows-latest
    needs: job1
    strategy:
     matrix:
      host: ${{fromJSON(needs.job1.outputs.vapps)}}
      include: 
      - bundle: ${{needs.job1.outputs.product}}
    steps:
      - name: install ${{matrix.include.bundle}} on ${{matrix.host.ip_address}}
        run: echo "installation will start on"
 
