name: Test Get-IP

on:
  workflow_dispatch:
   inputs:
    testSet:
      description: 'Testset JSON file.Separated by comma (,)'
      default: ""
      required: true
      type: string       
jobs:
  job1:
    runs-on: [windows-latest]
    outputs:
      matrix: ${{ steps.test-matrix.outputs.matrix }}
    
    
    steps:
      - uses: actions/checkout@v3      

      - name: Create a matrix for test execution
        id: test-matrix
        run: |
          $inputString = "${{ github.event.inputs.testSet }}"
          $fileNames = $inputString -split ','
          $objects = $fileNames | ForEach-Object { [PSCustomObject]@{ 'test' = $_ } }
          $resultJson = $objects | ConvertTo-Json -Depth 100 -Compress  | ForEach-Object { $_ -replace '"', "'" } 
          echo "::set-output name=matrix::$resultJson"



  job2:
    runs-on: [windows-latest]
    needs: [job1]
    steps:
      - uses: actions/checkout@v3      

      - name: Create a matrix for test execution
        run: |
          echo "${{ needs.job1.outputs.matrix }}"
        
