name: Matrix Example

on: [push]
env:
  JSON_DATA: |
    {
      "products": [
        {
          "product": "ReferenceClient",
          "ip": "192.168.0.1"
        },
        {
          "product": "WINCCCA",
          "ip": "192.168.0.2"
        },
        {
          "product": "WINCCPRO",
          "ip": "192.168.0.3"
        },
        {
          "product": "WINCCPRO,LagecyPanel,FeatureConfiguration",
          "ip": "192.168.0.4"
        },
        {
          "product": "WINCCPRO,LegacyPanel",
          "ip": "192.168.0.5"
        }
      ]
    }

jobs:
  print-data:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      data: ${{fromJson($JSON_DATA).products.product[*]}}
    steps:
      - name: Print JSON Data
        run: |
          echo "hello"
