name: test-call

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch: 
    
jobs:

  job1:
    runs-on: windows-latest    

    steps:
      - name: Set color
        id: set-color-var
        run: echo "vapps=Hello" >> "$GITHUB_OUTPUT"  
        #shell: bash
      - name: print value
        run: echo "${{ steps.set-color-var.outputs.vapps }}"
      
         
    outputs:
      vapps: ${{ steps.set-color-var.outputs.vapps }} 
                
  get-color:
    runs-on: ubuntu-latest
    needs: job1
  
    steps:
      - name: print value
        run: echo "${{ needs.job1.outputs.vapps }}"
 
