name: test-call

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch: 
    
jobs:

  job1:
    runs-on: windows-latest    
    env:
      out: "[{'vapp_id': 'loadtest-0', 'ip_address': '149.212.205.9'}, {'vapp_id': 'loadtest-1', 'ip_address': '149.212.205.11'}]"
    steps:
      - name: Set color
        id: set-color-var
        run: "vapps=${{ env.out }}"
      #  run: echo "${{ steps.set-color-var.outputs.vapps }}"
      
         
    outputs:
      vapps: ${{ steps.set-color-var.outputs.vapps }} 
                
  get-color:
    runs-on: ubuntu-latest
    needs: job1
  
    steps:
      - name: print value
        run: echo "${{ needs.job1.outputs.vapps }}"
 
