name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
env:
  data: "[{'id': 't-0', 'ip_address': '1','template':'temp1','wait':30}, {'id': 't-1', 'ip': '11','template':'temp2','wait':60}]"

jobs:

  job1:
    runs-on: ubuntu-latest    

    steps:
      - name: Set color
        id: set-color-var
        run: echo "vapps=${{ env.data }}" >> "$GITHUB_OUTPUT"
         
         
         
    outputs:
      vapps: ${{steps.set-color-var.outputs.vapps}} 
      product: ${{ steps.set-product.outputs.product }}
                
  get-color:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
     matrix:
      host: ${{fromJSON(needs.job1.outputs.vapps)}}

    steps:
      - name: wait for ${{matrix.host.wait}}-${{matrix.host.wait}}
        run: sleep ${{matrix.host.wait}}
        
  set-color:
    runs-on: ubuntu-latest
    needs: [get-color,job1]
    strategy:
     matrix:
      host: ${{fromJSON(needs.job1.outputs.vapps)}}
    steps:
      - name: setting color for ${{matrix.host.id}}
        run: echo "operation"
