name: Matrix Example

on:
  push:
    branches:
      - testing

env:
  JSON_DATA: |
    [
      {
        "product": "ReferenceClient",
        "ip": "192.168.0.1"
      },
      {
        "product": "WINCCCA",
        "ip": "192.168.0.2"
      },
      {
        "product": "WINCCPRO",
        "ip": "192.168.0.3"
      },
      {
        "product": "WINCCPRO,LagecyPanel,FeatureConfiguration",
        "ip": "192.168.0.4"
      },
      {
        "product": "WINCCPRO,LegacyPanel",
        "ip": "192.168.0.5"
      }
    ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        product: ${{ fromJson(JSON_DATA) }}
    steps:
      - name: Use Matrix Value
        run: |
          echo "Product: ${{ matrix.product.product }}"
          echo "IP: ${{ matrix.product.ip }}"
