name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
env:
  MY_VARIABLE: initial_value

jobs:
  update_variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set initial value
        run: echo "MY_VARIABLE=initial_value" >> $GITHUB_ENV

      - name: Update variable
        run: echo "MY_VARIABLE=new_value" >> $GITHUB_ENV

      - name: Archive updated value
        uses: actions/upload-artifact@v2
        with:
          name: updated-value
          path: $GITHUB_ENV

  print_value:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for artifact
        uses: actions/github-script@v4
        with:
          script: |
            const artifact = await github.actions.waitForArtifact('updated-value');
            const download = await artifact.download();
            await download.saveDirectory('.');

      - name: Print updated value
        run: |
          value=$(cat updated-value)
          echo "Updated value: $value"
