name: Matrix Example

on:
  push:
    branches:
      - testing

env:
  JSON_DATA: |
    [
      {
        "ip": "192.168.0.1"
      },
      {
        "ip": "192.168.0.2"
      },
      {
        "ip": "192.168.0.3"
      },
      {
        "ip": "192.168.0.4"
      },
      {
        "ip": "192.168.0.5"
      }
    ]


jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Extract IP values
        id: extract
        run: |
          echo "::set-output name=ips::$(echo '${{ env.JSON_DATA }}' | jq -r '.[].ip')"

  test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ip: ${{ needs.prepare.outputs.ips }}
    steps:
      - name: Use Matrix Value
        run: |
          echo "IP: ${{ matrix.ip }}"
