name: Test Get-IP

on:
  workflow_dispatch:
   inputs:
    testSet:
      description: 'Testset JSON file.Separated by comma (,)'
      default: ""
      required: true
      type: string       
jobs:
  job1:
    runs-on: [windows-latest]
    strategy:
      matrix:
       tests: ["${{ github.event.inputs.testSet }}"]
    steps:
      - uses: actions/checkout@v3      

      - name: Create a matrix for test execution
        run: echo "running test for ${{matrix.tests}}"
