name: Matrix Example

on:
  push:
    branches:
      - testing

env:
  JSON_DATA: |
    [
      {
        'ip': '192.168.0.1'
      },
      {
        'ip': '192.168.0.2'
      }
    ]


jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      ip: ${{ steps.extract.outputs.ip }}
    steps:
      - name: Extract IP values
        id: extract
        run: |
          echo "${{ env.JSON_DATA }}" | jq -r '.[].ip' > ips.txt
          echo "::set-output name=ip::$(cat ips.txt)"

  test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ip: ${{ needs.prepare.outputs.ip }}
    steps:
      - name: Use Matrix Value
        run: |
          echo "IP: ${{ matrix.ip }}"
