name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
env:
  data: "[{'id': 't-0', 'ip_address': '1','template':'temp1','wait':30}, {'id': 't-1', 'ip': '11','template':'temp2','wait':600}]"

jobs:

  job1:
    runs-on: ubuntu-latest    
    strategy:
     matrix:
      host: ${{fromJSON(needs.job1.outputs.vapps)}}
    steps:
      - name: Set color
        id: set-color-var
        run:  echo "::set-output name=${{ matrix.host.template }}::completed"
         
         
         
    outputs:
      vapps: ${{steps.set-color-var.outputs.vapps}} 
      product: ${{ steps.set-product.outputs.product }}
                
  get-color:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
     matrix:
      test: ${{fromJSON(needs.job1.outputs.vapps)}}

    steps:
      - name: wait for ${{needs.job1.matrix.host.template}}
        run: sleep 0
        
