name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
env:
  data: "[{'id': 't-0', 'ip_address': '1','template':'temp1','wait':30}, {'id': 't-1', 'ip': '11','template':'temp2','wait':600}]"


jobs:
  matrix-job:
    strategy:
      matrix:
        job-1: [600,60]        

    runs-on: ubuntu-latest

    steps:
       - name: Steps for matrix-job
         run: sleep ${{matrix.job-1}}
    
       - name: Matrix Job
         run: |
          # Perform matrix job steps
          echo "::set-output name=completed_job::job-1"    

  
  next-job:
    needs: matrix-job

    if: ${{ always() }} # Ensures the job runs even if the previous jobs fail

    runs-on: ubuntu-latest

    steps:
      - name: Check if any matrix job is completed
        run: |
          if [[ -n "${{ needs.matrix-job.outputs.completed_job }}" ]]; then
            echo "completed"
          else
            echo "No matrix jobs have completed yet."
            exit 0
          fi
