name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
env:
  data: "[{'id': 't-0', 'ip_address': '1','template':'temp1','wait':30}, {'id': 't-1', 'ip': '11','template':'temp2','wait':600}]"
  prouct1: ""
jobs:

  job1:
    runs-on: ubuntu-latest    

    steps:
      - name: Set color
        id: set-color-var
        run: |
         echo "vapps=${{ env.data }}" >> "$GITHUB_OUTPUT"
         echo "$product1 = test" >> $GITHUB_ENV
         echo "${{env.product1}}"
         
         
         
    outputs:
      vapps: ${{steps.set-color-var.outputs.vapps}} 
                
