name: Example Workflow

on:
  push:
    branches:
      - main
env:
  JSON_DATA: |
    {
      "products": [
        {
          "product": "ReferenceClient",
          "ip": "192.168.0.1"
        },
        {
          "product": "WINCCCA",
          "ip": "192.168.0.2"
        },
        {
          "product": "WINCCPRO",
          "ip": "192.168.0.3"
        },
        {
          "product": "WINCCPRO,LagecyPanel,FeatureConfiguration",
          "ip": "192.168.0.4"
        },
        {
          "product": "WINCCPRO,LegacyPanel",
          "ip": "192.168.0.5"
        }
      ]
    }

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up strategy matrix
        id: setup_matrix
        run: |
          echo '${{ toJson($env.JSON_DATA) }}' > data.json
          # Replace <your JSON data> with the actual JSON data

          # Parse the JSON data and store it in a variable
          echo "::set-output name=data::$(cat data.json | fromJson)"

      - name: Use JSON data in strategy matrix
        run: |
          # Get the parsed JSON data from the previous step's output
          ${{ steps.setup_matrix.outputs.data }}

          # Create the strategy matrix using the parsed data
          strategy:
            matrix:
              product: ${{ fromJson(steps.setup_matrix.outputs.data).products[*].product }}
              ip: ${{ fromJson(steps.setup_matrix.outputs.data).products[*].ip }}

          # Print the values of the strategy matrix
          echo "Product: ${{ matrix.product }}"
          echo "IP: ${{ matrix.ip }}"
