name: Matrix Example

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build and test
        run: |
          npm install
          npm test

jobs:
  matrix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 12.x
          - 14.x
          - 16.x

    steps:
      - name: Generate Matrix
        id: matrix
        run: |
          echo "::set-output name=os::${{ join(matrix.os, ',') }}"
          echo "::set-output name=node-version::${{ join(matrix.node-version, ',') }}"

  build:
    needs: matrix
    runs-on: ${{ fromJson(needs.matrix.outputs.os) }}

    strategy:
      matrix:
        os: ${{ fromJson(needs.matrix.outputs.os) }}
        node-version: ${{ fromJson(needs.matrix.outputs.node-version) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build and test
        run: |
          npm install
          npm test
