name: Matrix Example

on: [push]

env:
  JSON_DATA: |
   [
        {
          "product": "ReferenceClient",
          "ip": "192.168.0.1"
        },
        {
          "product": "WINCCCA",
          "ip": "192.168.0.2"
        },
        {
          "product": "WINCCPRO",
          "ip": "192.168.0.3"
        },
        {
          "product": "WINCCPRO,LagecyPanel,FeatureConfiguration",
          "ip": "192.168.0.4"
        },
        {
          "product": "WINCCPRO,LegacyPanel",
          "ip": "192.168.0.5"
        }
      ]

jobs: 
 set:
  runs-on: ubuntu-latest
  steps:
   - name: set
     id: set-val
     run: echo "vapps=${{ env.test }}" >> "$GITHUB_OUTPUT"
  outputs:
      vapps: ${{steps.set-val.outputs.vapps}} 
 test:
    runs-on: ubuntu-latest
    needs: set
    steps:
      - name: Use Matrix Values
        run: echo "${{ needs.set.outputs.vapps}}"
