name: workflow-call 
on:
  workflow_call:
    inputs:
      testbatch:
        required: true
        type: string       
jobs:
  innerloop:
    runs-on: windows-latest  
    strategy:
      matrix:
       testsets:[set1,set2,set3]
    
    steps:
      - name: print array
        shell: pwsh
        run: echo Run ${{ matrix.testsets }}
