name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
    
jobs:

  job1:
    runs-on: ubuntu-latest    

    steps:
      - name: Set color
        env:
         test: "[{'vapp_id': 'loadtest-0', 'ip_address': '149.212.205.9'}, {'vapp_id': 'loadtest-1', 'ip_address': '149.212.205.11'}]"
        id: set-color-var
        run: echo "vapps=${{ env.test }}" >> "$GITHUB_OUTPUT"
    
      - name: get ip
        id: get-ip
        run: echo "ip=${{ fromJSON(steps.set-color-var.outputs.vapps).ip_address }}" >> "$GITHUB_OUTPUT"
       
         
         
    outputs:
      vapps: ${{ steps.set-color-var.outputs.vapps }} 
      ip: ${{ steps.get-ip.outputs.ip }}
                
  get-color:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
     matrix:
      host: ${{fromJSON(needs.job1.outputs.vapps).ip_address}}
      # ip: ${{ fromJSON(needs.job1.outputs.ip) }}
    steps:
      - name: install product on ${{matrix.host}}
        run: echo "installation will start"
 
