name: Matrix Example

on:
  push:
    branches:
      - testing

env:
  JSON_DATA: |
    [
      {
        'ip': '192.168.0.1'
      },
      {
        'ip': '192.168.0.2'
      }
    ]


jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      ip: ${{ steps.extract.outputs.ip }}
    steps:
      - name: Extract IP values
        id: extract
        run: echo "COUNT=${{env.JSON_DATA}}" >> $env:GITHUB_OUTPUT

  test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ip: ${{ needs.prepare.outputs.ip }}
    steps:
      - name: Use Matrix Value
        run: |
          echo "IP: ${{ matrix.ip }}"
