name: Matrix Example

on: [push]

env:
  JSON_DATA: |
    {
      "products": [
        {
          "product": "ReferenceClient",
          "ip": "192.168.0.1"
        },
        {
          "product": "WINCCCA",
          "ip": "192.168.0.2"
        },
        {
          "product": "WINCCPRO",
          "ip": "192.168.0.3"
        },
        {
          "product": "WINCCPRO,LagecyPanel,FeatureConfiguration",
          "ip": "192.168.0.4"
        },
        {
          "product": "WINCCPRO,LegacyPanel",
          "ip": "192.168.0.5"
        }
      ]
    }

jobs:
  generate-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Use Environment Variable
        run: echo "JSON Data ${{ env.JSON_DATA }}"

      - name: Create Matrix
        id: create_matrix
        run: |
          echo "${{ env.JSON_DATA }}" > jsonfile.json
          matrix=$(jq -r '.products | map("\(.product):\(.ip)") | join(" ")')
          echo "::set-output name=matrix::$matrix"

  run-tests:
    needs: generate-matrix
    strategy:
      matrix:
        include:
           ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    runs-on: ubuntu-latest

    steps:
      - name: Print Matrix
        run: echo ${{ matrix.product }}:${{ matrix.ip }}

      - name: Run Tests
        run: |
          echo "Running tests for ${{ matrix.product }} with IP ${{ matrix.ip }}"
