name: Matrix Example

on: [push]
env:
  JSON_DATA: |
    {
      "products": [
        {
          "product": "ReferenceClient",
          "ip": "192.168.0.1"
        },
        {
          "product": "WINCCCA",
          "ip": "192.168.0.2"
        },
        {
          "product": "WINCCPRO",
          "ip": "192.168.0.3"
        },
        {
          "product": "WINCCPRO,LagecyPanel,FeatureConfiguration",
          "ip": "192.168.0.4"
        },
        {
          "product": "WINCCPRO,LegacyPanel",
          "ip": "192.168.0.5"
        }
      ]
    }
jobs:
  parse-json:
    runs-on: ubuntu-latest
    outputs:
      products: ${{ steps.parse-json.outputs.products }}
      ips: ${{ steps.parse-json.outputs.ips }}
    steps:
      - name: Parse JSON
        id: parse-json
        run: |
          echo "${{ env.JSON_DATA }}" > json_file
          echo "::set-output name=products::$(jq -r '.products[].product' json_file)"
          echo "::set-output name=ips::$(jq -r '.products[].ip' json_file)"

  test:
    needs: parse-json
    runs-on: ubuntu-latest
    #strategy:
     # matrix:
      #  product: ${{ fromJson(needs.parse-json.outputs.products) }}
       # ip: ${{ fromJson(needs.parse-json.outputs.ips) }}

    steps:
      - name: Use Matrix Values
        run: |
          echo "${{needs.parse-json.outputs.products}}"
