name: Matrix Example

on: [push]

env:
  JSON_DATA: |
    {
      "products": [
        {
          "product": "ReferenceClient",
          "ip": "192.168.0.1"
        },
        {
          "product": "WINCCCA",
          "ip": "192.168.0.2"
        },
        {
          "product": "WINCCPRO",
          "ip": "192.168.0.3"
        },
        {
          "product": "WINCCPRO,LagecyPanel,FeatureConfiguration",
          "ip": "192.168.0.4"
        },
        {
          "product": "WINCCPRO,LegacyPanel",
          "ip": "192.168.0.5"
        }
      ]
    }

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Use Matrix Values
        run: echo "${{env.JSON_DATA}}"
