name: Matrix Example

on: [push]
env:
  JSON_DATA: |
    {
      "products": [
        {
          "product": "ReferenceClient",
          "ip": "192.168.0.1"
        },
        {
          "product": "WINCCCA",
          "ip": "192.168.0.2"
        },
        {
          "product": "WINCCPRO",
          "ip": "192.168.0.3"
        },
        {
          "product": "WINCCPRO,LagecyPanel,FeatureConfiguration",
          "ip": "192.168.0.4"
        },
        {
          "product": "WINCCPRO,LegacyPanel",
          "ip": "192.168.0.5"
        }
      ]
    }
jobs:
  extract_products:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Product Names
        id: extract
        run: |
          echo "${{ env.JSON_DATA }}" > data.json
          products=$(jq -r '.products[].product' data.json)
          echo "::set-output name=products::$products"

  test:
    needs: extract_products
    runs-on: ubuntu-latest
    strategy:
      matrix:
        product: ${{ steps.extract.outputs.products }}
    steps:
      - name: Use Matrix Value
        run: echo "Product ${{ matrix.product }}"
