name: Matrix Example

on: [push]

jobs:
  print-data:
    runs-on: ubuntu-latest

    steps:
      - name: Print JSON Data
        run: |
          echo '${{ toJSON([
            {
              "product": "ReferenceClient",
              "ip": "192.168.0.1"
            },
            {
              "product": "WINCCCA",
              "ip": "192.168.0.2"
            },
            {
              "product": "WINCCPRO",
              "ip": "192.168.0.3"
            },
            {
              "product": "WINCCPRO,LagecyPanel,FeatureConfiguration",
              "ip": "192.168.0.4"
            },
            {
              "product": "WINCCPRO,LegacyPanel",
              "ip": "192.168.0.5"
            }
          ]) }}'
