name: Matrix Example

on: [push]

env:
  JSON_DATA: |
    {
      "products": [
        {
          "product": "ReferenceClient",
          "ip": "192.168.0.1"
        },
        {
          "product": "WINCCCA",
          "ip": "192.168.0.2"
        },
        {
          "product": "WINCCPRO",
          "ip": "192.168.0.3"
        },
        {
          "product": "WINCCPRO,LagecyPanel,FeatureConfiguration",
          "ip": "192.168.0.4"
        },
        {
          "product": "WINCCPRO,LegacyPanel",
          "ip": "192.168.0.5"
        }
      ]
    }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Environment Variable
        run: echo "JSON Data ${{ env.JSON_DATA }}"

      - name: Generate Matrix
        id: create_matrix
        run: |
          echo "${{ env.JSON_DATA }}" > jsonfile.json
          matrix=$(pwsh -Command "$json = Get-Content -Raw jsonfile.json | ConvertFrom-Json; $matrix = $json.products | foreach { '`"product`": `"$($_.product)`", `"ip`": `"$($_.ip)`"' }; Write-Host $matrix")
          echo "MATRIX=$matrix" >> $GITHUB_ENV

  test:
    needs: build
    strategy:
      matrix:
        include: ${{ matrix(env.MATRIX) }}

    runs-on: ubuntu-latest

    steps:
      - name: Use Matrix Values
        run: echo "Product ${{ matrix.product }}, IP ${{ matrix.ip }}"
