name: Matrix Example

on:
  push:
    branches:
      - testing

env:
  JSON_DATA: |
    [
      {
        "ip": "192.168.0.1"
      },
      {
        "ip": "192.168.0.2"
      },
      {
        "ip": "192.168.0.3"
      },
      {
        "ip": "192.168.0.4"
      },
      {
        "ip": "192.168.0.5"
      }
    ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ip: ${{ fromJson(env.JSON_DATA)[*].ip }}
    steps:
      - name: Use Matrix Value
        run: |
          echo "IP: ${{ matrix.ip }}"
