name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
env:
  product1: initial_value
  product2: initial_value

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      product1: ${{ steps.update_product1.outputs.product1 }}
    steps:
     
      - name: wait
        run: sleep 60

      - name: Update Product1 Variable
        run: echo "product1=done" >> $GITHUB_ENV

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Check Product1 Status
        run: |
          while [[ "${{ env.product1 }}" != "done" ]]; do
            echo "Product1 status: ${{ env.product1 }}"
            sleep 5
          done
          echo "Product1 is done!"
