name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
env:
  MY_VARIABLE: initial_value

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variable
        run: echo "MY_VARIABLE=new_value" >> $GITHUB_ENV

      - name: Display Environment Variable
        run: echo "The value of MY_VARIABLE is ${{ env.MY_VARIABLE }}"
