name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
env:
  product1: initial_value
  product2: initial_value

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
     
      - name: wait
        run: sleep 60
      - name: Update Product1 Variable
        run: echo "::set-output name=product1::done"

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Check Product1 Status
        run: |
          while [[ "${{ needs.job1.outputs.product1 }}" != "done" ]]; do
            echo "Product1 status: ${{ needs.job1.outputs.product1 }}"
            sleep 5
          done
          echo "Product1 is done!"
