name: Get-IP

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
env:
  MY_VARIABLE: initial_value

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: wait
        run: sleep 60
     
      - name: Set Environment Variable
        run: echo "MY_VARIABLE=new_value" >> $GITHUB_ENV

      - name: Display Environment Variable
        run: echo "The value of MY_VARIABLE is ${{ env.MY_VARIABLE }}" 

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Desired Value
        id: wait_for_value
        run: |
         while true; do
            workflow_run=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}")
            desired_value=$(echo "$workflow_run" | jq -r '.workflow_run.event.data.MY_VARIABLE')
            if [[ "$desired_value" == "desired_value" ]]; then
              echo "::set-output name=desired_value_found::true"
              break
            fi
            echo "Waiting for desired value..."
            sleep 5
          done
          echo "value found"
