name: Matrix Example

on: [push]

env:
  JSON_DATA: |
    {
      "products": [
        {
          "product": "ReferenceClient",
          "ip": "192.168.0.1"
        },
        {
          "product": "WINCCCA",
          "ip": "192.168.0.2"
        },
        {
          "product": "WINCCPRO",
          "ip": "192.168.0.3"
        },
        {
          "product": "WINCCPRO,LagecyPanel,FeatureConfiguration",
          "ip": "192.168.0.4"
        },
        {
          "product": "WINCCPRO,LegacyPanel",
          "ip": "192.168.0.5"
        }
      ]
    }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Environment Variable
        run: echo "JSON Data ${{ env.JSON_DATA }}"

      - name: Create Matrix
        id: create_matrix
        run: |
          echo "${{ env.JSON_DATA }}" > jsonfile.json
          $json = Get-Content -Raw jsonfile.json | ConvertFrom-Json
          $matrix = $json.products | ForEach-Object {
            [PSCustomObject]@{
              product = $_.product
              ip = $_.ip
            }
          } | ConvertTo-Json -Depth 100
          echo "::set-output name=matrix::$matrix"

      - name: Print Matrix
        run: echo ${{ steps.create_matrix.outputs.matrix }}



  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
       matrix:
        matrix: ${{ fromJson(build.create_matrix.outputs.matrix) }}
    steps:
    - name: print
      run: echo "Running tests for ${{ matrix.product }} with IP ${{ matrix.ip }}"
