name: workflow-call

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      testbatch:
        required: true
        type: string      

jobs:
  innerloop:
    runs-on: [ self-hosted ]
    strategy:
      matrix: 
        testsets: [set1,set2]

    steps:
    - name: print array      
      run: echo Run ${{ matrix.testsets }}
